### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#919]
I just pulled 427e90224109ff430, and HS won't build on 10.11.5.

```
$ git clean -fdx
$ make
mkdir -p build
echo "Building Hammerspoon in Debug configuration"
Building Hammerspoon in Debug configuration
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration Debug clean build > build/Debug-build.log
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/chdiza/Library/Developer/Xcode/DerivedData/Hammerspoon-fcxdlorvdthemyfxvlslfamwkvhz/Build/Intermediates/Hammerspoon.build/Debug/http.build/Objects-normal/x86_64/internal.o extensions/http/internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
```

If I go look in the file `build/Debug-build.log`, I see:
```
/source/hammerspoon/extensions/http/internal.m:149:21: error: use of undeclared identifier 'L'
            lua_pop(L, 1) ; // remove error message from stack
                    ^
1 error generated.
```

**Comment by asmagill** [comment]
My bad... tested it locally first, but then since it was a one-liner, just updated master directly.  It should work now.

**Comment by chdiza** [comment]
It does, thanks!
