### ISSUE TITLE
Build fails on El Capitan

### ISSUE THREAD

**Issue by chdiza** [Hammerspoon/hammerspoon#1691]
I just tried building on ElCap, and I got this at the terminal:
```
 make release
mkdir -p build
echo "Building Hammerspoon in Release configuration"
Building Hammerspoon in Release configuration
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release -configuration Release clean build > build/Release-build.log
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/chdiza/Library/Developer/Xcode/DerivedData/Hammerspoon-adlzscacpnutjgcpsrpwvdewubqc/Build/Intermediates/Pods.build/Release/CocoaLumberjack.build/Objects-normal/x86_64/DDOSLogger.o CocoaLumberjack/Classes/DDOSLogger.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
```

I inspected the log and found this:
```
/opt/bld/hammerspoon/Pods/CocoaLumberjack/Classes/DDOSLogger.m:51:8: error: unexpected '@' in program
    if(@available(iOS 10.0, macOS 10.12, tvOS 10.0, watchOS 3.0, *)) {
       ^
1 error generated.
```

**Comment by chdiza** [comment]
Bisection reveals that the first bad commit is 81600ac.

**Comment by latenitefilms** [comment]
Doh! @cmsj updated CocoaAsyncSocket and CocoaLumberjack on my suggestion, but the new releases mustn't be compatible with El Capitan.

**Comment by asmagill** [comment]
More likely an older version of XCode... the @available directive was added in XCode 9 or thereabouts.

**Comment by chdiza** [comment]
Yeah, El Cap can't use Xcode 9.  What's going to happen?  Is El Cap support going to be dumped?

**Comment by cmsj** [comment]
So, this is a bit tricky to untangle. We still have the deployment target set as 10.10, so the official builds should still be fine on ElCap, but keeping things such that they build on 10.10/10.11 is going to be much harder to figure out. Do you do any code modifications? or are you just building locally to be up to date with master? At some point I was doing some work on getting nightly builds going, but it stalled and I don't remember why. I could try and resurrect that effort?

**Comment by chdiza** [comment]
@cmsj I don't do any code modifications.  On that El Cap machine I just build every few weeks to be up to date with master (on my *real* machines I build to detect bugs early and try out new features).  The machine in question is kind of a tertiary backup, so it wouldn't hurt anything in my workflow if I gave up building HS on it and just downloaded prebuilt copies.

Nightlies seem like a good idea anyway, provided it's not too much effort.  Weeklies would also be fine, at least for my purposes.

**Comment by cmsj** [comment]
fwiw you should also be able to copy over your builds from other machines to the ElCap one. I'll try and find some time to figure out the nightly/weekly/whatever builds soon :)
